# Generated by Django 5.1.1 on 2024-09-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
