name: Manual Deployment to Vercel

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_PO049L6IKWhSj3GuG92iXht5mkmR/XA7Sfa4MPN"